version: '3.7'

volumes:
  postgres:

services:
  postgres:
    image: mdillon/postgis
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  seacrifog-api-dev:
    container_name: seacrifog-api-dev
    restart: always
    build: ./seacrifog-api
    ports:
      - 4000:3000

  seacrifog-client-dev:
    container_name: seacrifog-client-dev
    restart: always
    build: ./seacrifog-client
    ports:
      - 4001:80