version: '3.7'

services:
  postgres:
    image: postgis/postgis:14-3.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  seacrifog-api-dev:
    container_name: seacrifog-api-dev
    restart: always
    build: ./api
    ports:
      - 4000:3000

  seacrifog-client-dev:
    container_name: seacrifog-client-dev
    restart: always
    build: ./client
    ports:
      - 4001:80