name: DEPLOYMENT

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
    - name: Run a one-line script
      run: docker --help > test.log
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
